### ISSUE TITLE
provide cli command to view logs for an added  datasource 

### ISSUE THREAD

**Issue by ArulJeyananth** [datasage-io/datasage-cli#4]
./datasage-cli logs -datasource analytics -database dbname -table employee -format json -output c:/tmp/scanlog.json
Note:- 
-database dbname -table employee are optional

**Comment by aloksharma20** [comment]
command to view logs
./datasage-cli logs --datasource analytic --json
./datasage-cli logs --database dpdatasource --json
./datasage-cli logs --table datasource --json
./datasage-cli logs --json
./datasage-cli logs --csv
