### ISSUE TITLE
correct user info while adding data source

### ISSUE THREAD

**Issue by ArulJeyananth** [datasage-io/datasage-cli#7]
Show proper user info while adding datasource
May be below is the sequence of steps and actions

Connection established
Submitted for Database scanning
Class  & tag mapping completed
System Recommend following policies. (audit mode policies should be shown here)
  GDPR Audit
  PII Audit
 SOC 2 Audit
 HIPAA Audit
 UDI Audit
 

  
Do you want to Apply the policies?
 Choose/Type all - for applying all policies 
 Choose/Type list of  policies to be applied 

Ref:

**Comment by ArulJeyananth** [comment]
design : 
Use the same rpc service ( no need to go to stream )
Make multiple calls from client
@aloksharma20

**Comment by ArulJeyananth** [comment]
Step1:
   rpc Add ( addRequest ) returns (  messageResponse );
Step2: 
 rpc Scan( datasourceID ) returns (  messageResponse );
On success message may be like : Connection established; Submitted for Database scanning
On Error message may be like : Connection Failed
 
Step3:
rpc GetStaus ( datasourceID ) returns (  StatusResponse );
message may be any of the following
 Database scanning completed /
Class & tag mapping completed /
 
Step4:
Recommended Policies 
rpc GetRecomendedPolicies  ( datasourceID ) returns (  messageResponse );

System Recommend following policies. (audit mode policies should be shown here)
GDPR Audit
PII Audit
SOC 2 Audit
HIPAA Audit
UDI Audit
Step4:
rpc ApplyPolicies  ( datasourceID,policyID [] int) returns (  messageResponse );

Do you want to Apply the policies?
Choose/Type all - for applying all policies
Choose/Type list of policies to be applied

**Comment by aloksharma20** [comment]
- Server needs to send back the response and client will be print the response .
- Client doesn't know, what processes has been done on server. 
- @ArulJeyananth

**Comment by ArulJeyananth** [comment]
StatusResponse{

DataSourceAddFailed =1
DataSourceAddedSucessful =2
DataSourceScanInprogress=
DataSourceInitialScanFailed =
DataSourceInitialScanCompleted =
DataSourcePeriodicScanFailed =
DataSourcePeriodicScanCompleted =
DefaultPoliciesIdentificationFailed =
DefaultPoliciesIdentified =
PolicyEnforcementCompleted = 
PolicyEnforcementFailed =

}

**Comment by ArulJeyananth** [comment]
StatusResponse{

DataSourceAddFailed =1
DataSourceAddedSucessful =2
DataSourceInitialScanFailed =3
DataSourceInitialScanInprogress =4
DataSourceInitialScanCompleted =
DataSourcePeriodicScanFailed =
DataSourcePeriodicScanCompleted =
DefaultPoliciesIdentificationFailed =
DefaultPoliciesIdentified =
PolicyEnforcementCompleted = 
PolicyEnforcementFailed =

}

**Comment by ArulJeyananth** [comment]
scanResponse,err := Scan(northwind)
 err != nil
	DISPLAY DataSourceScanSubmitFailed
	END;
 else
 {
		DISPLAY DataSourceScanSubmitSucessful
		DISPLAY DataSourceScanInprogress

		//periodically check for the status of Scan n (100) times (n is coming from app config file datasage-cli.yaml
		repeat(  n times)
		{
			//wait for m seconds and get status
			sleep(m ) // m also come from config file
			dsStatus,err := getStatus((dsname)
			if dsStatus == DataSourceInitialScanCompleted || DataSourcePeriodicScanCompleted 
				DISPLAY DataSourceScanCompleted
				
				stat,err:=GetRecomendedPolicies ()
				if err == nil
					DISPLAY DefaultPoliciesIdentified
					DISPLAY choose all or enter  policy IDs
						applyPolicy()
						DISPLAY PolicyApplied
						END;
				

	
	
		}

 }

**Comment by aloksharma20** [comment]
https://github.com/datasage-io/datasage-cli/pull/15
